# Database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/SocialMedia
    driverClassName: org.postgresql.Driver
    username: postgres
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS


server:
  port: 1111
